# Site settings
title: Sparky Speaks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sparky speaks is a blog by me, sparky, and you can come on by to my shop "Sparky's Pet Salon" and say hi!.
baseurl: "/sparkyspeaks" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: sparkyspetsalon
github_username:  SparkysPetSalon

# Build settings
markdown: kramdown
