# Site settings
title: Sparky Speaks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Salon Hours: 
  Tuesday - Saturday 8am to 6pm 
  Sunday - Monday Closed
  407-864-0015
baseurl: "/sparkyspeaks" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: sparkyspetsalon
github_username:  SparkysPetSalon

# Build settings
markdown: kramdown
